### ISSUE TITLE
链接

### ISSUE THREAD

**Issue by prprnya** [prprnya/prprnya.github.io#3]
https://ruavan.com/links/ 

 如何添加友链 在评论区填写如下内容 1 2 3 4 - title:标题description:描述website:网站链接image:头像链接 然后等某只

**Comment by prprnya** [comment]
```yaml
- title: Van Nya Stew
  description: 爱掉毛的prpr喵
  website: https://ruavan.com
  image: https://avatars.githubusercontent.com/u/49584196
```

**Comment by 2X-ercha** [comment]
烷喵居然换博客了？而且没把窝的友链弄上去！可恶可恶啊（抓住透一透！

```yml
- title: 贰猹的小窝
  description: 用这生命中的每一秒，给自己一个不后悔的未来
  website: https://noionion.top/
  image: https://pub-noionion.oss-cn-hangzhou.aliyuncs.com/head.jpg
```
